// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelerikUI.Repository;

namespace TelerikUI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190409005540_initial_data_seed")]
    partial class initial_data_seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TelerikUI.Models.Material", b =>
                {
                    b.Property<string>("MaterialName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Manufacturer");

                    b.HasKey("MaterialName");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            MaterialName = "1",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "2",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "3",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "4",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "5",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "6",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "7",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "8",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "9",
                            Manufacturer = "Advantech"
                        },
                        new
                        {
                            MaterialName = "10",
                            Manufacturer = "Advantech"
                        });
                });

            modelBuilder.Entity("TelerikUI.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("FinishDate");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = "1",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 638, DateTimeKind.Local).AddTicks(9706)
                        },
                        new
                        {
                            OrderId = "2",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 647, DateTimeKind.Local).AddTicks(9232)
                        },
                        new
                        {
                            OrderId = "3",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 647, DateTimeKind.Local).AddTicks(9870)
                        },
                        new
                        {
                            OrderId = "4",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 647, DateTimeKind.Local).AddTicks(9928)
                        },
                        new
                        {
                            OrderId = "5",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 647, DateTimeKind.Local).AddTicks(9973)
                        },
                        new
                        {
                            OrderId = "6",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 648, DateTimeKind.Local).AddTicks(26)
                        },
                        new
                        {
                            OrderId = "7",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 648, DateTimeKind.Local).AddTicks(71)
                        },
                        new
                        {
                            OrderId = "8",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 648, DateTimeKind.Local).AddTicks(115)
                        },
                        new
                        {
                            OrderId = "9",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 648, DateTimeKind.Local).AddTicks(157)
                        },
                        new
                        {
                            OrderId = "10",
                            StartDate = new DateTime(2019, 4, 8, 17, 55, 39, 648, DateTimeKind.Local).AddTicks(206)
                        });
                });

            modelBuilder.Entity("TelerikUI.Models.SystemMaterial", b =>
                {
                    b.Property<Guid>("SystemMaterialId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MaterialName");

                    b.Property<string>("SN")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SystemSerialId");

                    b.HasKey("SystemMaterialId");

                    b.HasIndex("MaterialName");

                    b.HasIndex("SystemSerialId");

                    b.ToTable("SystemMaterials");

                    b.HasData(
                        new
                        {
                            SystemMaterialId = new Guid("a5e53837-a20b-4c0e-8de9-cbd6950543ea"),
                            MaterialName = "1",
                            SystemSerialId = 1
                        },
                        new
                        {
                            SystemMaterialId = new Guid("065c2969-9fdc-42a2-9bc9-accec9857e45"),
                            MaterialName = "2",
                            SystemSerialId = 2
                        },
                        new
                        {
                            SystemMaterialId = new Guid("8f6fef39-05e5-45ea-adb8-4f895a1be0e4"),
                            MaterialName = "3",
                            SystemSerialId = 3
                        },
                        new
                        {
                            SystemMaterialId = new Guid("da4a422b-526f-46b6-b433-f994c2876d85"),
                            MaterialName = "4",
                            SystemSerialId = 4
                        },
                        new
                        {
                            SystemMaterialId = new Guid("3686d152-1a31-48ce-ad93-6f420d5cf6df"),
                            MaterialName = "5",
                            SystemSerialId = 5
                        },
                        new
                        {
                            SystemMaterialId = new Guid("9e6e180f-966c-457b-9ed0-052f7b239aed"),
                            MaterialName = "6",
                            SystemSerialId = 6
                        },
                        new
                        {
                            SystemMaterialId = new Guid("6f195afd-ff3d-42ba-9bc2-7b4bc7d69097"),
                            MaterialName = "7",
                            SystemSerialId = 7
                        },
                        new
                        {
                            SystemMaterialId = new Guid("21a3c6b2-bc58-4408-b885-cbf4984f13b4"),
                            MaterialName = "8",
                            SystemSerialId = 8
                        },
                        new
                        {
                            SystemMaterialId = new Guid("8ed0779d-0738-4c2c-a9fd-8f34a32bbc4a"),
                            MaterialName = "9",
                            SystemSerialId = 9
                        },
                        new
                        {
                            SystemMaterialId = new Guid("87a41731-6ff6-4b33-8b78-61ee1a13eb53"),
                            MaterialName = "10",
                            SystemSerialId = 10
                        });
                });

            modelBuilder.Entity("TelerikUI.Models.SystemSerial", b =>
                {
                    b.Property<int>("SystemSerialId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrderId");

                    b.HasKey("SystemSerialId");

                    b.HasIndex("OrderId");

                    b.ToTable("SystemSerials");

                    b.HasData(
                        new
                        {
                            SystemSerialId = 1,
                            OrderId = "1"
                        },
                        new
                        {
                            SystemSerialId = 2,
                            OrderId = "2"
                        },
                        new
                        {
                            SystemSerialId = 3,
                            OrderId = "3"
                        },
                        new
                        {
                            SystemSerialId = 4,
                            OrderId = "4"
                        },
                        new
                        {
                            SystemSerialId = 5,
                            OrderId = "5"
                        },
                        new
                        {
                            SystemSerialId = 6,
                            OrderId = "6"
                        },
                        new
                        {
                            SystemSerialId = 7,
                            OrderId = "7"
                        },
                        new
                        {
                            SystemSerialId = 8,
                            OrderId = "8"
                        },
                        new
                        {
                            SystemSerialId = 9,
                            OrderId = "9"
                        },
                        new
                        {
                            SystemSerialId = 10,
                            OrderId = "10"
                        });
                });

            modelBuilder.Entity("TelerikUI.Models.SystemMaterial", b =>
                {
                    b.HasOne("TelerikUI.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialName");

                    b.HasOne("TelerikUI.Models.SystemSerial", "System")
                        .WithMany()
                        .HasForeignKey("SystemSerialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TelerikUI.Models.SystemSerial", b =>
                {
                    b.HasOne("TelerikUI.Models.Order", "Order")
                        .WithMany("SystemSerials")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
